### ISSUE TITLE
Error while launching from Snakefile

### ISSUE THREAD

**Issue by Overcraft90** [eblerjana/pangenie#17]
Hi there,

My aim is to get a genome inference for a human sample (HG005) to benchmark my graph in terms of SVs calling using `PanGenIe`. I assembled both with `minigraph-CACTUS` (for which I'm testing right now) and with `pggb`.

With that said, despite the pangenomes are quite small (only five individuals), after correctly outputting the _**.vcf**_ files for both of them, I incur in an error when launching from _Snakefile_. Below the output for the command:

```
File "Snakefile", line 13
    rule all:
           ^
SyntaxError: invalid syntax
```

Now, the reason I'm doing this is because of the **non-overlapping variants** requirement. Therefore, considering my _**.vcf**_ haven't been generated using your pipeline, I'm assuming they are not in accordance to the specific standard you mentioned (particularly the third one); hence why, I proceeded this way.

One last mention, I'm not very experience with _Snakefiles_, and after looking online I've seen they are launched invoking python3; is that the correct way? Let me know, thanks in advance!

P.S. attached a version of the _**.yaml**_ edited to conform the inputs for the script ([config.log](https://github.com/eblerjana/pangenie/files/9447837/config.log))

**Comment by ASLeonard** [comment]
You launch snakefiles with [snakemake](https://github.com/snakemake/snakemake), not with python3.

**Comment by eblerjana** [comment]
Exactly, in order to run the snakefile, use the following command: `snakemake --use-conda`

**Comment by Overcraft90** [comment]
Hi again,

After few attempts I got my `Snakemake` environment going on the cluster. However, following what @eblerjana suggested I incur in this error:

> Building DAG of jobs...
> MissingRuleException:
> No rule to produce Snakefile (if you use input functions make sure that they don't raise unexpected exceptions).

The actual command I run is `snakemake --cores 48 --use-conda Snakefile` within the **_snakemake_** Conda environment, let me know how I can address this issue. Thanks in advance!

**Comment by Overcraft90** [comment]
As an update to the previous message, I've been able to successfully run the tool. I think we can close this issue for now, thanks again!
