### ISSUE TITLE
Counting kmers from reads uses too much memory compared to jf

### ISSUE THREAD

**Issue by ASLeonard** [eblerjana/pangenie#2]
Hi Jana,

I've noticed that the memory usage when counting kmers directly from reads (and not a .jf) is incredibly high, and it looks like PanGenie reads the [entire fastq file into memory](https://github.com/eblerjana/pangenie/blob/842d97d2ceb039aad29c985cea83402c76efd1c9/src/jellyfishcounter.cpp#L39) and then counts the kmers. I think this also leads to under reporting of usage, because the PanGenie log for a run says
```
Count kmers in genome ...
#### Memory usage until now: 61.7867 GB ####
Determine unique kmers ...
#### Memory usage until now: 79.1394 GB ####
....
Total maximum memory usage: 84.4493 GB
```

When the same cluster reports peak usage of 223.6 Gb. At one point during kmer counting it was 176.3 Gb, so it definitely seems like the kmer counting is a big bottleneck, especially for moderate/high coverage samples.

Just running jellyfish by itself to produce the .jf file only peaked at 42.1 Gb, so that seems like a better approach currently.

I tried and very strongly failed at trying to implement some streaming feature in jellyfish. It looks like they have some code set up for that, but I didn't last long enough.

**Comment by eblerjana** [comment]
> Hi Jana,
> 
> I've noticed that the memory usage when counting kmers directly from reads (and not a .jf) is incredibly high, and it looks like PanGenie reads the [entire fastq file into memory](https://github.com/eblerjana/pangenie/blob/842d97d2ceb039aad29c985cea83402c76efd1c9/src/jellyfishcounter.cpp#L39) and then counts the kmers. I think this also leads to under reporting of usage, because the PanGenie log for a run says
> 
> ```
> Count kmers in genome ...
> #### Memory usage until now: 61.7867 GB ####
> Determine unique kmers ...
> #### Memory usage until now: 79.1394 GB ####
> ....
> Total maximum memory usage: 84.4493 GB
> ```
> 
> When the same cluster reports peak usage of 223.6 Gb. At one point during kmer counting it was 176.3 Gb, so it definitely seems like the kmer counting is a big bottleneck, especially for moderate/high coverage samples.
> 
> Just running jellyfish by itself to produce the .jf file only peaked at 42.1 Gb, so that seems like a better approach currently.
> 
> I tried and very strongly failed at trying to implement some streaming feature in jellyfish. It looks like they have some code set up for that, but I didn't last long enough.

PanGenie does not read the whole fastq into memory. The part you are referring to is just parsing the filename, not the content of the file. 

It's weird that you observed such a high memory usage. What is reported in the log corresponds to the peak memory usage and for me, this number always matched to the Maximum resident set size reported by `/usr/bin/time -v`.  Can you share the full log file? What input data are you using (coverage of reads/number of samples in VCF)?

**Comment by eblerjana** [comment]
> Interesting just noticed that the histograms are slightly different. The jf was generated as
> 
> ```
>  jellyfish count -m 31 -o test.jf -s 3000000000 -C -t 12 test.fasta
> ```
> 
> which generated about 50% more values in the histogram (mostly different from counts 1 to 4), so not sure if there is bloom filter or different setting used by PanGenie I missed.


These are the parameters PanGenie uses for jellyfish:
```
	const uint64_t hash_size    = hash; // Initial size of hash, default = 3000000000.
	const uint32_t num_reprobes = 126;
	const uint32_t num_threads  = nr_threads; // Number of concurrent threads
	const uint32_t counter_len  = 7;  // Minimum length of counting field
	const bool canonical = true; // Use canonical representation
```
You can try using exactly these, I guess this should then give the same results.


> In the jellyfishcounter there is a part where its `jellyfish::mer_dna::k()*2)` and in jellyfishreader where its ` jellyfish::mer_dna::k(this->header->key_len() / 2);`, so not sure if that is related, where something isn't being set correctly at the right time.

This should be unrelated, the first one is setting the number of bits to use for the keys of the kmers (2 bits per base), the second one does the opposite in order to derive the kmer size fro the key length

**Comment by ASLeonard** [comment]
Testing those parameters explicitly now, but according to the jellyfish --help, reprobes and counter len default to 126 and 7, so excluding the concurrency, all the parameters should already be identical to what PanGenie calls.

The result of calling with fastq vs jf does seem to change the resulting _genotyping.vcf files as well, with different GQ:GL:KC tags, so the kmer difference isn't just in the histogram reporting.

**Comment by ASLeonard** [comment]
Got pretty much the same results with those explicit parameters. Something must be up in how low frequency kmers are treated.
| f(k) | jellyfish | PanGenie |
|------|-----------|----------|
| 1    | 944916965 | 3878109  |
| 2    | 27002685  | 4172061  |
| 3    | 13295405  | 8103416  |
| 4    | 17163555  | 14081917 |
| 5    | 24342943  | 21695478 |
| 6    | 33334412  | 30731103 |
| 7    | 44012008  | 41452023 |
| 8    | 56929516  | 54506911 |
| 9    | 72761748  | 70557072 |
| 10   | 91465262  | 89518897 |
Whereas they become increasingly similar above this point

**Comment by eblerjana** [comment]
PanGenie per default only counts those kmers in the reads that are present in the pangenome graph, i.e. the path_segments.fasta and ignores all other kmers. If you run jellyfish like you did above, it counts all kmers that it sees in the reads. This is why the results are different, especially for the low frequency kmers.

**Comment by ASLeonard** [comment]
Ah that is exactly it. Running jellyfish with additional parameters of `-L 1 -U 10000 --if <*path_segments.fasta>` produces identical output now to the fastq PanGenie histogram.

I'm rerunning now with `/usr/bin/time -v`, so hopefully that will be informative.

The query is around 18x paired-end coverage, 10 samples in the panel (with 16,696,339 variants). Here is a log file for one of the runs.

[lsf.o204129701.txt](https://github.com/eblerjana/pangenie/files/8040534/lsf.o204129701.txt)

**Comment by eblerjana** [comment]
From the cluster output you pasted above, it is not clear what is measured here exactly. I would assume that these numbers correspond to the virtual memory usage. If that is the case, then this does not tell you how much (physical) memory PanGenie actually used. Instead, the output of `/usr/bin/time` confirms that the actual memory usage of PanGenie is around 85GB, so this all looks totally fine to me.

**Comment by ASLeonard** [comment]
So I've been using valgrind to check into this, and ended up install jellyfish from source so I could more easily change the cxx flags. Now the cluster memory report matches the pangenie one. It was pretty reproducible to use 150+ Gb before when counting kmers and is now reproducible to match the pangenie numbers, so maybe this is something related to how conda installs jellyfish? Is that what you were using?

**Comment by eblerjana** [comment]
I'm not sure I understand, but it seems you were measuring two different things, the virtual memory usage and the physical memory usage (which is the only number that matters here, virtual memory usage is not telling you how much memory is actually used). Can you explain what exactly you ran and how you compared the results? What does the 150GB correspond to? What does valgrind report?

That PanGenie and jellyfish have different memory usages is not surprising, since there is several other things happening in PanGenie in addition to just counting the kmers (such as additionally counting graph kmers, constructing a pangenome graph, etc.)

**Comment by ASLeonard** [comment]
Sorry it became a bit convoluted. I'm not 100% clear on virtual vs physical memory, but our cluster will kill jobs that are using more "memory" than requested, so my jobs were being killed even when requesting 100 Gb and PanGenie was reporting usage of 80 Gb. So whatever the difference in definition, this was causing problems.

To summarise 

## Using PanGenie with jellyfish installed through conda
Memory used when 
- fastq input (PanGenie counts k-mers through jellyfish API): 150+ Gb
  - **does not** match rusage output
- jf input (PanGenie reads k-mers counted directly by jellyfish): 80 Gb
  - **does** match rusage output

## Using PanGenie with jellyfish install from source
- fastq input (PanGenie counts k-mers through jellyfish API): 90 Gb
  - **does** match rusage output
- jf input (PanGenie reads k-mers counted directly by jellyfish): 80 Gb
  - **does** match rusage output

## Valgrind
Super slow (especially single-threaded), but no meaningful memory leaks when run with a very reduced dataset. Using the massif tool also seemed to show there isn't anything crazy going on with the heap allocation, but still running this with a full dataset (painfully slow).

**Comment by eblerjana** [comment]
I see. I'm not sure I can do anything about it without knowing what exactly is measured by your cluster. The `/usr/bin/time `output as well as PanGenie's log output both confirm that the (actual) memory usage is around 80GB (which is as expected). If what your cluster measures here is indeed virtual memory usage, then this is difficult to control, because it might be dependent on properties of the machine you are running on. So if using jellyfish compiled from source in PanGenie solves this issue, then I think the easiest solution is to use this. As an alternative you could also try installation in a Singularity container as mentioned in the README as an alternative to using conda.
