### ISSUE TITLE
Which version of CHM13 reference genome to use

### ISSUE THREAD

**Issue by Han-Cao** [eblerjana/pangenie#31]
Hi,

Thanks for developing this great tool. I would like to use the "HPRC-CHM13 (88 haplotypes)" variant reference. Based on the name, I think the reference genome I should use for genotyping is CHM13, but I am not sure which version of CHM13 to use. Could you provide links to the reference genome you used when generating the variant reference vcf?

Thanks,
Han

**Comment by eblerjana** [comment]
Hi Han, 

I'm using this reference: https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph/CHM13v11Y.fa.gz

Best,
Jana

**Comment by Han-Cao** [comment]
Hi Jana,

Thanks a lot! This is really helpful.

Best,
Han
