### ISSUE TITLE
Question about std::runtime_error

### ISSUE THREAD

**Issue by whyskyisgray** [eblerjana/pangenie#37]
Hello,

I've encountered the following error while running a program:

The input file used is the output from minigraph-cactus.

When I created the input VCF using only 3 genome sequences, the calling worked well. However, after adding 200 more genomes, I faced the following error

Can anyone help me resolve this issue?

Thank you.

###
$ pangenome singularity exec $programs/pangenie/container/pangenie.sif PanGenie -i 10-5.fastq -r $ref -v ./pangenome.vcf -l 31 -j 4 -t 4 -o 10-5 -s 10-5

program: PanGenie - genotyping and phasing based on kmer-counting and known haplotype sequences.
author: Jana Ebler

Files and parameters used:
-a	0
-c	0
-d	0
-e	3000000000
-g	0
-i	10-5.fastq
-j	4
-k	31
-o	10-5
-p	0
-r	./cw_final.fasta
-s	10-5
-t	4
-u	0
-v	./pangenome.vcf
Determine allele sequences ...
Found 11 chromosome(s) from the reference file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  VariantReader: number of paths is limited to 254 in current implementation.
[1]    229709 abort (core dumped)  singularity exec $programs/pangenie/container/pangenie.sif PanGenie -i  -r  -

**Comment by eblerjana** [comment]
Hi, as mentioned in the PanGenie README, the current implementation limits the panel size to 254 haplotypes. Currently the focus of PanGenie is whole genome haplotype-resolved assemblies of human genomes where the number of fully assembled haplotypes is still much smaller

**Comment by whyskyisgray** [comment]
Thank you for your kind answer!!
Have a nice day!
