### ISSUE TITLE
How to get the correct reference file and variants file

### ISSUE THREAD

**Issue by DiWangShePi** [eblerjana/pangenie#40]
Hello.

I am a beginner in this field and I'm currently trying to learn how to use this tool. In regard to the input files for this tool, I have a very naive question.

I would like to use some larger datasets to run this program. I found some relevant information in the paper's link, such as this link: https://zenodo.org/record/5607680. However, the FASTA files in this link seem to be categorized by genotypes. How can I extract information about a single chromosome from these files and then obtain corresponding reference and variant files that match each other?

Best.

**Comment by eblerjana** [comment]
Hi,

which files in this repository are you referring to exactly? Existing input data sets that can be used with PanGenie are listed in the README ("Data and genotypes"). I would use these instead, as they are newer and consist of larger panels compared to the data that was used in the PanGenie publication. PanGenie should always be run on the full genome. After genotyping, you can extract certain regions from the VCF using tools like `bcftools`.

Best,
Jana

**Comment by DiWangShePi** [comment]
Hello,

I have solved this problem with the file mentioned in this issue (https://github.com/eblerjana/pangenie/issues/31), thank you very much for your reply

Have a nice day!
Best,
DiWangShePi
