### ISSUE TITLE
Install from source error in v3.0

### ISSUE THREAD

**Issue by wjwei-handsome** [eblerjana/pangenie#41]
Hi @eblerjana ,

For the newest code in `master` branch, I encountered some errors like this:

```sh
[  1%] Building CXX object src/CMakeFiles/PanGenieLib.dir/emissionprobabilitycomputer.cpp.o
In file included from /public/home/wjwei/SFTW/pangenie-3.0.0/src/uniquekmers.hpp:9,
                 from /public/home/wjwei/SFTW/pangenie-3.0.0/src/emissionprobabilitycomputer.hpp:8,
                 from /public/home/wjwei/SFTW/pangenie-3.0.0/src/emissionprobabilitycomputer.cpp:5:
/public/home/wjwei/SFTW/pangenie-3.0.0/src/kmerpath.hpp:8:10: fatal error: cereal/access.hpp: No such file or directory
    8 | #include <cereal/access.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/PanGenieLib.dir/emissionprobabilitycomputer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/PanGenieLib.dir/all] Error 2
make: *** [all] Error 2
``` 

After using conda to create a env, `cereal` are here:

```sh
ll /public/home/wjwei/SFTW/conda/envs/pangenie/include/cereal/
total 515K
-rw-rw-r-- 2 wjwei JBYan  15K Feb 28  2022 access.hpp
drwxr-xr-x 2 wjwei JBYan 4.0K Aug 22 21:48 archives/
-rw-rw-r-- 2 wjwei JBYan  47K Feb 28  2022 cereal.hpp
drwxr-xr-x 2 wjwei JBYan 4.0K Aug 22 21:48 details/
drwxr-xr-x 4 wjwei JBYan 4.0K Aug 22 21:48 external/
-rw-rw-r-- 2 wjwei JBYan 6.6K Feb 28  2022 macros.hpp
-rw-rw-r-- 2 wjwei JBYan 6.5K Feb 28  2022 specialize.hpp
drwxr-xr-x 3 wjwei JBYan 4.0K Aug 22 21:48 types/
-rw-rw-r-- 2 wjwei JBYan 2.4K Feb 28  2022 version.hpp
``` 

So, I'm confused about the source-code install.

Looking forward to your reply sincerely.

Best wishes, Wei

**Comment by eblerjana** [comment]
How did you install PanGenie? Within the provided conda environment following the steps provided in the README?

**Comment by eblerjana** [comment]
And in case you are using the conda environment, did you re-build it using the latest environment file in the master branch? Because this file was updated with the merge as well

**Comment by wjwei-handsome** [comment]
> How did you install PanGenie? Within the provided conda environment following the steps provided in the README?

I installed it by source-code and conda like this:

```sh
git clone https://github.com/eblerjana/pangenie.git  
cd pangenie  
conda env create -f environment.yml  
conda activate pangenie   
mkdir build; cd build; cmake .. ; make
```

**Comment by wjwei-handsome** [comment]
> And in case you are using the conda environment, did you re-build it using the latest environment file in the master branch? Because this file was updated with the merge as well

Sure, the newest file `environment.yml` is in the master branch, and it certainly contained `cereal=1.3.2=hd8ed1ab_0`

**Comment by wjwei-handsome** [comment]
Hi @eblerjana , when i tried cleaning all my conda envs and re-create env, problem seems solved. I guess some dependency conflict is causing the problem.

Thanks!!
