### ISSUE TITLE
PanGenie installation by conda

### ISSUE THREAD

**Issue by lx-1011** [eblerjana/pangenie#46]
Dear @eblerjana,
    Thank you for this useful tool. I have a question about Pangenie installation.

#h**ere is the pangenie installation method I chose**
git clone https://github.com/eblerjana/pangenie.git
cd pangenie
conda env create -f environment.yml
conda activate pangenie
mkdir build; cd build; cmake .. ; make
#(pangenie) cche@login02 21:25:03
 ~/lixin/software/pangenie/build
$ 
make
[ 37%] Built target PanGenieLib
[ 40%] Built target PanGenie
[ 42%] Built target PanGenie-index
[100%] Built target tests

**#but PanGenie can't run after 'make' process**
(pangenie) cche@login02 22:07:42
 ~/lixin/software/pangenie/build
$ 
PanGenie
bash: PanGenie: command not found...
    
    Would you mind helping me?
    Thanks and wish you all the best.
    Li Xin

**Comment by dmjask** [comment]
Hi, i'm experiencing the same issue. What is the solution?

**Comment by eblerjana** [comment]
After installation from source using the conda environment, you have to run PanGenie like this:
`./build/src/PanGenie`
Have you tried that?

**Comment by dmjask** [comment]
Initially it failed to run with that command, but after reinstalling PanGenie has run succesfully.
Thanks!
