### ISSUE TITLE
Truncated genotyping

### ISSUE THREAD

**Issue by Sunhh** [eblerjana/pangenie#48]
Hi Jana,

I ran PanGenie for genotyping on my own dataset, and it finished without errors or warnings. However, I found on all 11 chromosomes, the genotyping results stopped too early, around 11 Mb or 13 Mb while the the chromosome length should be close to 30 Mb.
What is your recommendation to solve this problem?

Thank you!

Honghe

**Comment by Sunhh** [comment]
Hi Jana,

Thank you for your reply! My output has the same variant record number as
the input, but after some position of each chromosome, all the following
positions are called as missing (./.). I found this problem disappeared
after I removed the ‘-u’ parameter. I didn’t see anything abnormal in the
log.

Best regards,
Honghe

**Comment by eblerjana** [comment]
if you use the -u parameter, PanGenie reports genotype „./.“ for all variants not covered by any unique kmers. So I guess in your case, there are no unique kmers for these variants.

**Comment by Sunhh** [comment]
Hi Jana,

Then that'll be really weird to me. For each of the 11 chromosomes I have, the genotypes after ~ 10-13 Mb are all "./.". Considering my chromosome length ranges 28-38 Mbp, I cannot believe the rest 20 Mbp have no unique kmers at all. Besides, subsetting the reads with only those mapped to the un-genotyped regions could produce genotypes for some region but again after some position, all the following genotypes were "./.". However, I feel without "-u" parameter, my results look good.
Since I can do genotyping without "-u" well, I think my problem has been solved well. I'll close this issue.

Thank you!

Best regards,
Hognhe

> if you use the -u parameter, PanGenie reports genotype „./.“ for all variants not covered by any unique kmers. So I guess in your case, there are no unique kmers for these variants.
