### ISSUE TITLE
GraphBuilder: Found invalid genotype. (Minigraph cactus vcf)

### ISSUE THREAD

**Issue by duelstrobe** [eblerjana/pangenie#56]
Hello, 

I'am trying to genotype short reads using pangenie but during the indexing step with the vcf output of minigraph cactus i'am encountering this error: 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  GraphBuilder::GraphBuilder: Found invalid genotype. Genotypes must be diploid (.|. if missing).
Aborted (core dumped)
```

Here is a sample from my minigraph cactus vcf : 
```
chr1    13551   >2370>2374      T       C,A     60.0    .       AC=1,16;AF=0.0434783
=>2370>2371>2374,>2370>2373>2374,>2370>2372>2374;NS=23;LV=0     GT      0       2   2       2       2       2       2       2       .       .       .       .       2   2       0       .       2       .       0       0       2       2       0       1   .       2       .
```

I'am not working on the human genome so i can't use the pre-processing pipeline, does my vcf need pre-processing after minigraph cactus (apart from vcfbub).

Thank you beforehand.

**Comment by eblerjana** [comment]
The problem is that the VCF contains haploid genotypes. PanGenie expects diploid genotypes in the input panel, since the underlying model is designed for diploid species.

**Comment by duelstrobe** [comment]
That makes sense, thank you.
