### ISSUE TITLE
How to translate the MC vcf result to pangenie pipeline

### ISSUE THREAD

**Issue by ld9866** [eblerjana/pangenie#58]
Dear developer：
We all know that the vcf result from Minigraph-cactus is a single allelic, we have no problem using vcfbub filtering, but how we should convert to the biallelic same as the test example which is very confusing to us.
Thank you!

**Comment by eblerjana** [comment]
Hi,

the Minigraph-Cactus pipeline produces a diploid VCF file when run on haplotype-resolved assemblies (i.e. one assembly per haplotype). As explained in the README, PanGenie expects a diploid VCF generated from such haplotype-resolved assemblies. Thus, PanGenie is not suited for panels generated from assemblies that are not haplotype-resolved, as it models recombination between haplotypes.

**Comment by ld9866** [comment]
Thank you!
