### ISSUE TITLE
update help/readme: uncompressed input

### ISSUE THREAD

**Issue by ptrebert** [eblerjana/pangenie#6]
The command line help is accurate (`reads.fa/fq`), but since uncompressed read files are uncommon, it would be helpful to add that requirement in a more obvious way, e.g.

```
-i VAL	sequencing reads in FASTA/FASTQ format or Jellyfish database in jf format (required).
        NOTE: INPUT FASTA/Q FILE MUST NOT BE COMPRESSED
```

**Comment by vb-ak** [comment]
I would like to add to this: compressed fastq/bam/cram input would be incredibly useful from a practical standpoint. Is that on the roadmap by any chance?

**Comment by cgroza** [comment]
Yes, currently we are using PanGenie and we have to uncompress input file all the time.

**Comment by eblerjana** [comment]
Note that you can also use `-i <(gunzip -c reads.fq.gz)` in case of a single FASTA/FASTQ file or  `-i <(zcat sample.R1.fq.gz sample.R2.fq.gz)`  in case of two FASTA/FASTQ files to provide the input reads to PanGenie.

**Comment by vb-ak** [comment]
Oh now that is super helpful. Thank you!
