### ISSUE TITLE
ployploid allele frequency

### ISSUE THREAD

**Issue by sdws1983** [eblerjana/pangenie#60]
Hello, 

I'm currently trying to perform polyploid population analysis using PanGenie. I am using a haploid reference genome and aligning the existing polyploid genomes to it to obtain a VCF file, then running PanGenie with the following command:

```
PanGenie -f all.combined.PanGenie -i <(zcat trim_PE1.fq.gz trim_PE2.fq.gz) -s L000 -o L000 -j 24 -t 24
```

In the resulting VCF file, I'm interested in using the AF field as a polyploid allele frequency for downstream analysis. Could you confirm if this approach is feasible?

Thanks!

Yumin

**Comment by eblerjana** [comment]
Hi,

as mentioned in the README, PanGenie was designed for diploid species only (with a focus on human). It expects a diploid VCF and also produces diploid genotypes. Furthermore, the model assumes recombination in a diploid genome. I would not recommend using it for polyploid data, as I'm not sure whether it will produce any meaningful results for polyploid data sets.

Best,
Jana
