### ISSUE TITLE
How to retain only the STRUCTURE VARIATION for pangenie

### ISSUE THREAD

**Issue by ld9866** [eblerjana/pangenie#69]
Dear developer
We want to only make use of pangenie for group typing from the result of Minigraph-cactus. 

How do we delete snp and indel, because we feel that adding a large amount of snp and inde variation information will make the time of genotypeing.

Best yours!

**Comment by eblerjana** [comment]
PanGenie needs information from SNPs+indels for the imputation of genotypes in regions not well covered by k-mers. Therefore, it is not recommended to remove any of these variants prior to genotyping.

**Comment by ld9866** [comment]
Thank you for your help and relpy!
