### ISSUE TITLE
update help/readme: output prefix

### ISSUE THREAD

**Issue by ptrebert** [eblerjana/pangenie#7]
It is not obvious how PanGenie handles the output prefix if the path includes non-existent folders. By looking at the runtime errors, I assume PanGenie does not create non-existent folders.

**Comment by eblerjana** [comment]
Indeed the directories in the prefix must exist already. I added details to the command line help and also the code now throws a proper error in case the prefix contains non-existing directories.

**Comment by ptrebert** [comment]
Great, thanks!
