### ISSUE TITLE
pangenie-index failed: std::runtime_error, "Hash full"

### ISSUE THREAD

**Issue by leleory** [eblerjana/pangenie#74]
Hi Jana,

I was in the process of indexing a cactus-pangenome based variant callset (seven diploids). The variants were filtered with vcfbub. I tested pangenie by running it with data on a single chromosome and it worked OK.

When I tried it on the full dataset the indexing step failed with the following lines:

`pangenie-index -r $infa -v $invcf -o idx -e 100000`

> GraphBuilder: skip variant at sscro11_Y:42522731 since alleles contain undefined nucleotides: T,TCTCTCTCTCTCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCTCTCTCT
> GraphBuilder: skip variant at sscro11_Y:43174887 since alleles contain undefined nucleotides: CAACACAAAACCAGGTTCAAGGAATATTGAAAGGGCTTCTCTAAACCAAAAAGTAAGGAAGGAAAGGAAGAAAAAGAAAAGAAAAAAAAAAGAAGAAGAAGAAGAGGAAGAACTAGGACTGAGGAAACCGCAATCAGAGAGCAGTCACTC,CNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> Identified 21347831 variants in total from VCF-file.
> Write path segments to file ...
> Found 347 chromosome(s) in the VCF.
> Count kmers in graph ...
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Hash full
> 

Can you please tell me what does the error "Hash full" means and how can I overcome this problem?

Thank you,
Lel

**Comment by eblerjana** [comment]
Hi Lel,

I'd assume this is either because not enough memory is available on the machine or due to the `-e 100000` parameter which sets the hash size. For a whole genome dataset, I would not recommend using this parameter, this is mainly meant to be used for demo purposes (see README). 

Best,
Jana

**Comment by leleory** [comment]
This should then be the -e parameter, as only half of the allocated memory was used by pangenie-index. 
Thank you,
Lel
