### ISSUE TITLE
How the callset vcf generated. 

### ISSUE THREAD

**Issue by GooLey1025** [eblerjana/pangenie#91]
Ather fininshing the Pangenie, I want to follow the script convert_to_biallelic.py. 
` cat <pangenie-output> | python3 convert-to-biallelic.py <callset-VCF>  > callset-genotypes.vcf`

How the [callset vcf](https://zenodo.org/record/7839719/files/chm13_cactus_filtered_ids_biallelic.vcf.gz?download=1) generated. 
I check the **chm13_cactus_filtered_ids_biallelic.vcf.gz**. detail info see the picture below.
I guess it was based on MC-pipeline output vcf. Then it was processed by `bcftools --min-ac 1` and `--trim-alt-allels` like the red mark in the picture. And also `bcftools norm -m -any` to generate bialleic.vcf. But I do not know how the INFO filed has ID information, e.g ID=chr1-11715-SNV->19323>19324>19326-1.
![图片](https://github.com/user-attachments/assets/31514391-339f-4e18-bbb3-b13b1d06edc6)
Can you tell me how this generated by some tools? And for further, What is the difference between using bcftools norm and convert_to_bialleic.py to generate biallelic variants.

I would appreciate it for your any reply. Much thanks for the software developer.

**Comment by eblerjana** [comment]
The `convert-to-biallelic.py` script can only be applied to the PanGenie-ready VCFs liked in the README, or to VCFs generated from Minigraph-Cactus graphs based on this pipeline: https://github.com/eblerjana/genotyping-pipelines/tree/main/prepare-vcf-MC. Please read the Wiki (https://github.com/eblerjana/pangenie/wiki/A:--Genotyping-variation-nested-inside-of-bubbles) on what it does exactly. It's purpose is to convert bubble genotypes to genotypes for nested variants. `bcftools norm` simply splits multiallelic records into biallelic ones by listing each allele as a separate record.

**Comment by GooLey1025** [comment]
Thanks for your response. After thoroughly reviewing and reflecting on the wiki multiple times, I believe I have finally developed a much deeper and more nuanced understanding of the topic.

**Comment by wuxiaopei0509** [comment]
A great work for pangenome genotyping, I have a question, the pipeline  (https://github.com/eblerjana/pangenie/wiki/A:--Genotyping-variation-nested-inside-of-bubbles)  were suitble for plant pangenomes and how to use it ? Namely,  how to get the Pangenie inputs from MC output vcf ?
